# This is the configuration file for pre-commit hooks.
# It specifies which hooks to run before each commit.

repos:
  # Define the local repository containing the hooks.
  - repo: local # Indicates that the hook is defined locally rather than fetched from a remote repository.

    # List the hooks to run from this local repository.
    hooks:
      - id: ruff # The ID of the hook to run. This is a unique identifier for the hook.
        name: Check with Ruff # A descriptive name for the hook.
        entry: poetry run ruff # The command to run when the hook is triggered. It runs Ruff using Poetry.
        language: system # Specifies that the hook uses the system's language environment.
        pass_filenames: false # Indicates that filenames should not be passed to the command. Ruff will determine which files to check.
        always_run: true # Ensures that the hook runs on every commit, regardless of the files changed.
        args: ["check", "--fix"] # Additional arguments for the command. In this case, it runs Ruff in check mode on the current directory and applies fixes.
